// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdqKb41VQvZR2mzHH4gBqBVa2agBYXtxk',
    appId: '1:633974904096:web:17928718e8c64566173345',
    messagingSenderId: '633974904096',
    projectId: 'fasum-billa',
    authDomain: 'fasum-billa.firebaseapp.com',
    storageBucket: 'fasum-billa.appspot.com',
    measurementId: 'G-GVMFQDD0X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGxBglFs6EsdfosQQ5z6qUNRjSesBdbM',
    appId: '1:633974904096:android:05990e8ef1bdf360173345',
    messagingSenderId: '633974904096',
    projectId: 'fasum-billa',
    storageBucket: 'fasum-billa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLkWvcqG_kRR5bTrxROWbAij5v7p99Rg',
    appId: '1:633974904096:ios:1943748208a9067d173345',
    messagingSenderId: '633974904096',
    projectId: 'fasum-billa',
    storageBucket: 'fasum-billa.appspot.com',
    iosClientId: '633974904096-tsutqlbc8h9pkms9eohl4e0dfiiirn3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumBila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaLkWvcqG_kRR5bTrxROWbAij5v7p99Rg',
    appId: '1:633974904096:ios:1943748208a9067d173345',
    messagingSenderId: '633974904096',
    projectId: 'fasum-billa',
    storageBucket: 'fasum-billa.appspot.com',
    iosClientId: '633974904096-tsutqlbc8h9pkms9eohl4e0dfiiirn3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumBila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdqKb41VQvZR2mzHH4gBqBVa2agBYXtxk',
    appId: '1:633974904096:web:81e978ed371b39b6173345',
    messagingSenderId: '633974904096',
    projectId: 'fasum-billa',
    authDomain: 'fasum-billa.firebaseapp.com',
    storageBucket: 'fasum-billa.appspot.com',
    measurementId: 'G-RPS4K80ZW1',
  );
}
